### ISSUE TITLE
Is vite chunking supported? 

### ISSUE THREAD

**Issue by bgr11n** [Valian/live_vue#18]
Hi. Sorry it is not an issue just have a question isvite chunking currently supported?

From what I saw how you are loading build result looks like no, could you please clarify?

Thank you!

**Comment by Valian** [comment]
Hi @bgr11n! I'm sorry for a slow response on my side. 

In the README vite chunking is named "lazy loading" and [is supported](https://github.com/Valian/live_vue?tab=readme-ov-file#lazy-loading-vue-components). Simply provide component as a function importing the component `() => import('./my_component.vue')` to LiveVue hook.  

When using chunking LiveVue [includes links](https://github.com/Valian/live_vue/blob/main/lib/live_vue.ex#L104) in SSR-rendered part so they load in parallel to the main `app.js` file.

Just, I must say that feature might not be fully polished. Why? I had some problems with hashing these chunks. Since Phoenix adds it's own hashes during `mix assets.deploy` it conflicted with chunk hashing from `vite`, so I had to disable these. It's part of the installation process, so should work out-of-the-box. It might make browser cache invalidation harder, though.  

Also, in some cases SSR was behaving in a weird way. But please try it and report any issues! 🙏

**Comment by bgr11n** [comment]
@Valian Thank you!

**Comment by tonydangblog** [comment]
> Just, I must say that feature might not be fully polished. Why? I had some problems with hashing these chunks. Since Phoenix adds it's own hashes during `mix assets.deploy` it conflicted with chunk hashing from `vite`, so I had to disable these. It's part of the installation process, so should work out-of-the-box. It might make browser cache invalidation harder, though.

@Valian Just a thought - I also had a Phoenix project with Vite and ran into the hashing conflict. I remember that I was able to get around it by using Vite hashes for the chunks only and have Phoenix hash the entry file only and everything seems to work. Running `phx.digest` will hash both the entry and chunk files, so you end up with extra files though. 

For example, Vite would generate:
`app.js`
`chunk-[vite-hash].js`

Then after `phx.digest` you end up with:
`app.js`
`app-[phx-hash].js`
`chunk-[vite-hash].js`
`chunk-[vite-hash]-[phx-hash].js`
 
Then in prod, `app-[phx-hash].js` will reference `chunk-[vite-hash].js` and ignore the ones that phoenix generated so there shouldn't be any conflict. I haven't worked on the project in a while though so I'm not sure if there's any edge cases I missed.

**Comment by Valian** [comment]
Thanks @tonydangblog! In the past I was experimenting exactly with what you said here and it was working, just there was one problem:

Chunks also can reference app.js, but they're not aware of phoenix-hashed name. 

So it looked like this:

1. app-[phx-hash].js was loaded
2. chunk-[vite-hash].js was loaded
3. chunk imported something from `app-[vite-hash].js` so `app-[vite-hash].js` was loaded as well

and I ended up with 2 copies of app.js being loaded. So all in all I dropped these vite-generated hashes, but possibly there's a better solution (maybe override hash of app.js in phoenix manifest?). Will investigate it further.

Thanks for your input!

**Comment by tonydangblog** [comment]
> 3. chunk imported something from `app-[vite-hash].js` so `app-[vite-hash].js` was loaded as well

@Valian Oh, I didn't think about this case!

I'll do more digging when I have time as well and will let you know if I find a solution. This is definitely a tough one 😅
