### ISSUE TITLE
Error running `mix assets.build` with Vue and Vite

### ISSUE THREAD

**Issue by SamuelBonilla** [Valian/live_vue#43]
#### **Description**
When attempting to run the `mix assets.build` task in a Phoenix project, errors occur depending on how the `build` script is defined in `package.json`.

#### **Steps to Reproduce**
1. Configure the `build` script in `package.json` as follows:
   ```json
   "build": "vue-tsc && vite build"
   ```
2. Run the following command:
   ```bash
   $ mix assets.build
   ```
3. Observe the error:
   ```
   /Users/sam/dev/elixir/phoenix/app/assets/node_modules/vue-tsc/index.js:34
               throw err;
               ^
   Search string not found: "/supportedTSExtensions = .*(?=;)/"
   (Use `node --trace-uncaught ...` to show where the exception was thrown)
   
   Node.js v22.2.0
   ** (exit) 1
   ```

4. Modify the `build` script to remove `vue-tsc`:
   ```json
   "build": "vite build"
   ```
5. Run the same command:
   ```bash
   $ mix assets.build
   ```
6. Observe a different error:
 
  ```
 > build
  > vite build
  
  vite v5.4.11 building for production...
  transforming...
  ✓ 69 modules transformed.
  x Build failed in 870ms
  error during build:
  [commonjs--resolver] Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
```

#### **Expected Behavior**
The `mix assets.build` command should complete successfully, building assets without errors.

#### **Actual Behavior**
- With `vue-tsc` included, the build fails with a search string error in `vue-tsc`.
- Without `vue-tsc`, the build fails with an invalid `output.format` error, referencing `UMD` and `IIFE` being unsupported for code-splitting builds.

#### **Environment**
- **Node.js version**: v22.2.0
- **Phoenix version**: 1.7.12
- **Dependencies**: Vue, Vite, Vue-TSC
- **Operating System**: macOS

**Comment by SamuelBonilla** [comment]
fix the first issue ( vue-tsc  )

https://github.com/nuxt/nuxt/issues/30026#issue-2687500330
https://github.com/vuejs/language-tools/issues/5018#issuecomment-2494783497

fix the second issue ( vite build )

https://github.com/vitejs/vite/issues/17483#issuecomment-2364116700

**Comment by Valian** [comment]
Hi @SamuelBonilla thanks for the report!

Is that error happening on a fresh install of LiveVue, without any configuration changes? Or you adjusted configuration / packages on your own? 

If yes, could you provide a repo with a reproduction? Your errors are related to module resolution and vite config, so both things are hard to spot without exact package versions and configuration files. 

According to the issues you posted, it might be an error in the newest TS version 🤔

**Comment by SamuelBonilla** [comment]
I have another issue with web workers, but I'll create another issue. Can we tackle this issue in this thread?

`Error in convertAndOptimize: SecurityError: Failed to construct 'Worker': Script at 'http://localhost:5173/js/worker.js?worker_file&type=module' cannot be accessed from origin 'http://localhost:4000'.
`

**Comment by Valian** [comment]
Ok I can confirm running `npm install -D typescript vue-tsc` installs latest versions which are currently broken. Didn't really though it could be an issue 😞 

I can pin them in the installation instructions but then I'll need to adjust them to new versions on my own, and it's a lot of work. So I'll add a note that users should downgrade typescript and vue-tsc if they stumble upon that error, and remove that note later after this issue is removed. 

Regarding workers - this project by default doesn't include any web workers. I see your project is trying to load one from `js/worker.js`. I have never tried using web workers with LiveVue yet, simply because I didn't had to. Still, I can add `worker: {format: 'es'}` to the default Vite config, I think it shouldn't hurt. 

About 

> Error in convertAndOptimize: SecurityError: Failed to construct 'Worker': Script at 'http://localhost:5173/js/worker.js?worker_file&type=module' cannot be accessed from origin 'http://localhost:4000'.

After some digging I don't think there's anything wrong in live_vue regarding this issue. See workaround in https://github.com/vitejs/vite/issues/13680

**Comment by sbonilla-godaddy** [comment]
thanks
